FROM gcc:latest

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential

# We adjusted the paths so that it copies from the 'server' folder
COPY server/src/ ./src/
COPY server/include/ ./include/

# We compile using the container's internal paths
RUN gcc src/*.c -I include -o server -lpthread

RUN mkdir -p logs

EXPOSE 8080

# The executable 'server' was placed in the root of /app
CMD ["./server", "8080", "logs/server.log"]